packages:
  - apps/*
  - packages/*

strictDepBuilds: true

allowBuilds:
  esbuild@0.28.1: true
  '@bundled-es-modules/glob': false
  style-dictionary: false

patchedDependencies:
  unconfig@7.5.0: patches/unconfig@7.5.0.patch

catalog:
  '@iconify-json/lucide': 1.2.120
  '@types/node': 24.13.3
  '@unocss/core': 66.7.5
  '@unocss/eslint-plugin': 66.7.5
  '@unocss/preset-icons': 66.7.5
  '@unocss/preset-wind4': 66.7.5
  '@vitejs/plugin-vue': 6.0.8
  colorjs.io: 0.7.1
  eslint: 10.8.0
  eslint-plugin-boundaries: 7.1.0
  eslint-plugin-vue: 10.10.0
  eslint-plugin-vuejs-accessibility: 2.5.0
  knip: 6.29.0
  prettier: 3.9.6
  stylelint: 17.14.1
  style-dictionary: 5.4.4
  tsx: 4.23.1
  typescript: 6.0.3
  typescript-eslint: 8.65.0
  unocss: 66.7.5
  vite: 8.1.5
  vue: 3.5.40
  vue-tsc: 3.3.8
  yaml: 2.9.0
  zod: 4.4.3
