/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    'console-overview': RouteRecordInfo<
      'console-overview',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'error-route-not-found': RouteRecordInfo<
      'error-route-not-found',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'appearance-management': RouteRecordInfo<
      'appearance-management',
      '/appearance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'capability-roadmap': RouteRecordInfo<
      'capability-roadmap',
      '/capabilities',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'design-token-inspector': RouteRecordInfo<
      'design-token-inspector',
      '/design-tokens',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'engineering-quality-inspector': RouteRecordInfo<
      'engineering-quality-inspector',
      '/engineering',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'error-invalid-route-input': RouteRecordInfo<
      'error-invalid-route-input',
      '/error/400',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'error-authentication-required': RouteRecordInfo<
      'error-authentication-required',
      '/error/401',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'error-permission-denied': RouteRecordInfo<
      'error-permission-denied',
      '/error/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'error-application-route-failure': RouteRecordInfo<
      'error-application-route-failure',
      '/error/500',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'error-service-unavailable': RouteRecordInfo<
      'error-service-unavailable',
      '/error/maintenance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'error-network-unavailable': RouteRecordInfo<
      'error-network-unavailable',
      '/error/offline',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'responsive-layout-inspector': RouteRecordInfo<
      'responsive-layout-inspector',
      '/responsive-layout',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'router-governance-inspector': RouteRecordInfo<
      'router-governance-inspector',
      '/router',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'runtime-kernel-inspector': RouteRecordInfo<
      'runtime-kernel-inspector',
      '/runtime-kernel',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'storage-persistence-inspector': RouteRecordInfo<
      'storage-persistence-inspector',
      '/storage',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'ui-system-inspector': RouteRecordInfo<
      'ui-system-inspector',
      '/ui-system',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | 'console-overview'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | 'error-route-not-found'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/appearance.vue': {
      routes:
        | 'appearance-management'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/capabilities.vue': {
      routes:
        | 'capability-roadmap'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/design-tokens.vue': {
      routes:
        | 'design-token-inspector'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/engineering.vue': {
      routes:
        | 'engineering-quality-inspector'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error/400.vue': {
      routes:
        | 'error-invalid-route-input'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error/401.vue': {
      routes:
        | 'error-authentication-required'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error/403.vue': {
      routes:
        | 'error-permission-denied'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error/500.vue': {
      routes:
        | 'error-application-route-failure'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error/maintenance.vue': {
      routes:
        | 'error-service-unavailable'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/error/offline.vue': {
      routes:
        | 'error-network-unavailable'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/responsive-layout.vue': {
      routes:
        | 'responsive-layout-inspector'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/router.vue': {
      routes:
        | 'router-governance-inspector'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/runtime-kernel.vue': {
      routes:
        | 'runtime-kernel-inspector'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/storage.vue': {
      routes:
        | 'storage-persistence-inspector'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/ui-system.vue': {
      routes:
        | 'ui-system-inspector'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
